all: lab2_1.c lab2_3.c lab2_5.c lab2_6.c lab2_7.c lab2_8.c
	gcc -o lab2_1 lab2_1.c
	gcc -o lab2_3 lab2_3.c
	gcc -o lab2_5 lab2_5.c 
	gcc -o lab2_6 lab2_6.c
	gcc -o lab2_7 lab2_7.c
	gcc -o lab2_8 lab2_8.c -lpthread

clean:; rm -f lab2_1 lab2_3 lab2_5 lab2_6 lab2_7 lab2_8
